feat: add bullinea and fix typos in README.md
Consensys/linea-token-list pull request #181
Opened 2024-07-15 22:40 UTC by henrygagnier

Action: add token + fix two typos in README.md
Context / rational:

Changed bellow to below and updateAt to updatedAt for clarity

PR checklist:
- [x] I've verified and published the contract source
- [x] I've kept the token list in alphabetical order based on token symbol
- [x] I've updated the `updatedAt` (and potentially `createdAt`) fields
- [x] I've updated the list version number as per README instruction

2024-07-18 10:07 UTC, thedarkjester submitted a review, later dismissed

2024-07-18 10:56 UTC, thedarkjester requested changes
Please could you move the token information into the following file (see Readme guidelines)

Fill out the [linea-mainnet-token-shortlist.json](https://github.com/Consensys/linea-token-list/blob/main/json/linea-mainnet-token-shortlist.json) with your token's information.

2025-06-09 16:58 UTC, alainncls commented
Hey @henrygagnier is this still required?

2025-06-12 20:24 UTC, alainncls commented
Don't hesitate to open a fresh PR if required

2025-06-12 20:24 UTC, closed without merging