Add Genesis token
Consensys/linea-token-list pull request #187
Opened 2024-10-29 09:17 UTC by Thisuu

2024-10-29 09:26 UTC, thedarkjester requested changes
Please could you verify the contract as mentioned in the main README
```
IMPORTANT: Before adding a new token, it is mandatory to verify the token's smart contract. This ensures the authenticity and security of the token. Contract verification should be done through [LineaScan's](https://lineascan.build/) or [Etherscan's](https://etherscan.io/) contract verification tools.
```

2024-10-29 12:15 UTC, Thisuu commented
> Please could you verify the contract as mentioned in the main README
> 
> ```
> IMPORTANT: Before adding a new token, it is mandatory to verify the token's smart contract. This ensures the authenticity and security of the token. Contract verification should be done through [LineaScan's](https://lineascan.build/) or [Etherscan's](https://etherscan.io/) contract verification tools.
> ```

Thanks for the heads up! Contract is now verified.

2024-10-30 09:32 UTC, thedarkjester commented on json/linea-mainnet-token-shortlist.json
> +      "name": "GENESIS",
Please could you correct the casing on the name
![image](https://github.com/user-attachments/assets/be6ce384-2f2e-45b6-a6ed-ed659e72d61f)

2024-10-30 11:40 UTC, Thisuu commented on json/linea-mainnet-token-shortlist.json
> +      "name": "GENESIS",
My bad, Fixed!

2024-10-30 12:12 UTC, thedarkjester approved these changes

2024-10-30 13:53 UTC, merged